library("FactoClass")
library("FactoMineR")
library("readxl")
library("textshape")
library("factoextra")
library("Factoshiny")
library("ade4")

I<-read_excel("C:/Users/Matt/Downloads/Bases de Datos/I.xlsx")
I<-as.data.frame(I)
I<-scale(I)
I<-textshape::column_to_rownames(I,loc=1)

Factoshiny(I)
res.MFA<-MFA(I,group=c(4,4,4,4,4,4,4,4,4,4),type=c('s','s','s','s','s','s','s','s','s','s'),name.group=c("2010", "2011","2012","2013","2014","2015","2016","2017","2018","2019"),graph=FALSE)
plot.MFA(res.MFA, choix="ind",lab.par=FALSE,title="Individual factor map")
plot.MFA(res.MFA, choix="var",habillage='group',title="Correlation circle")
plot.MFA(res.MFA, choix="group")
plot.MFA(res.MFA, choix="axes",habillage='group')
